# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frank < Formula
  desc "Config-driven Docker environment for Laravel development"
  homepage "https://github.com/phlisg/frank"
  version "1.9.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phlisg/frank/releases/download/v1.9.1/frank-darwin-amd64.tar.gz"
      sha256 "a0a3ebbbce3fb15134f88fb1f36607909b5ac8ae2f023f64b3a5fe2d0e81c34f"

      define_method(:install) do
        bin.install "frank"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phlisg/frank/releases/download/v1.9.1/frank-darwin-arm64.tar.gz"
      sha256 "b2eba362a2cb1e9058f30f1b2dc070dbd90a9884bf566386e16fec930a2b122b"

      define_method(:install) do
        bin.install "frank"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phlisg/frank/releases/download/v1.9.1/frank-linux-amd64.tar.gz"
      sha256 "d913880f566e5584e1898e3c85ecba1c2e6d6546c7a551a081e43b0b14905406"
      define_method(:install) do
        bin.install "frank"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phlisg/frank/releases/download/v1.9.1/frank-linux-arm64.tar.gz"
      sha256 "f9a8411fda11f14e838ad678158559526438841d675b5b920b84f30897a3afb8"
      define_method(:install) do
        bin.install "frank"
      end
    end
  end
end
