# This file was generated by GoReleaser. DO NOT EDIT.
cask "frank" do
  version "1.10.2"

  on_macos do
    on_intel do
      sha256 "4bc93c880f7f2ba149e53b5749880fb5714b78b6046cfa3d63126c8ebb46f92c"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "bcdb502896dfc2294a373b088be01ca0c92747103170608804b5d61d05159206"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f9bf00e4b9da46660549d266e6bf5b60f1cdba4219aca7949fcdf45aeb0e5aa"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "d0cdf4ae3aa2efda9b14fe81c11c9934184649b243b132cd1011725829943405"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-linux-arm64.tar.gz"
    end
  end

  name "frank"
  desc "Config-driven Docker environment for Laravel development"
  homepage "https://github.com/phlisg/frank"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frank"

  # No zap stanza required

end
