# This file was generated by GoReleaser. DO NOT EDIT.
cask "frank" do
  version "1.10.8"

  on_macos do
    on_intel do
      sha256 "64d1512a8a6f6fd958243e87c46256a6d484257d8cc8fbf85df4b7fb399a8052"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "7dc015534db05dd4c070c5ef07f964a7daef65bb77d3bfade33afefea4119f7c"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ef76d9fd91979ba180b7b18bc6b8deac29722e667828890dd80f44080a47d04"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "254273870ce6a5191a99c5f480f558c1384ee3e3e1ff7a3ae7a7980c0e82b1cd"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-linux-arm64.tar.gz"
    end
  end

  name "frank"
  desc "Config-driven Docker environment for Laravel development"
  homepage "https://github.com/phlisg/frank"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frank"

  # No zap stanza required

end
