# This file was generated by GoReleaser. DO NOT EDIT.
cask "frank" do
  version "1.14.2"

  on_macos do
    on_intel do
      sha256 "110e02e71b8ae1f135018730882d59a13fa2813abc6f997db9dbbe2755e0333a"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "c3fdc27c497e9cddc14d3d9b66e792448f951bbb99110cfa8ca3ceec34f1c725"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b9995e7de2dc83a41897755ffac75f91455aa2d019f92f96a3e21262eaa08e7d"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "3f3af87173b69cf155fe9f59b8599113d2acf7347cff8fa64864c7c37d150532"
      url "https://github.com/phlisg/frank/releases/download/v#{version}/frank-linux-arm64.tar.gz"
    end
  end

  name "frank"
  desc "Config-driven Docker environment for Laravel development"
  homepage "https://github.com/phlisg/frank"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frank"

  # No zap stanza required

end
